<a href="https://colab.research.google.com/github/Lukas-Swc/neural-network-course/blob/main/02_basics/02_activation_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Spis treści:
1. [Funkcje aktywacji](#a0)
    1. [Import bibliotek](#a1)
    2. [ReLU Function - Rectified Linear Unit](#a2)
    3. [Funkcja Sigmoid](#a3)
    4. [Tanh Function](#a4)
    5. [Funkcja Softmax](#a5)
  

### <a name='a0'></a> 1. Funkcje Aktywacji
#### <a name='a1'></a> 1.1 Import bibliotek

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import math

np.set_printoptions(precision=6)

#### <a name='a2'></a> 1.2 ReLU Function - Rectified Linear Unit
####     $$f(x) = max(x, 0)$$


In [16]:
def max_relu(x):
  return max(x, 0.0)

In [17]:
for i in [-10., -5., 0., 5., 10.]:
  print(max_relu(i))

0.0
0.0
0.0
5.0
10.0


In [18]:
data = np.random.randn(50)
data = sorted(data)
data

[np.float64(-2.600977881190556),
 np.float64(-1.7965976323600332),
 np.float64(-1.7545230781882482),
 np.float64(-1.3348030955814139),
 np.float64(-1.309235839374709),
 np.float64(-1.2496906664521814),
 np.float64(-1.1987099802773584),
 np.float64(-1.1524519595891878),
 np.float64(-1.0949327264733886),
 np.float64(-1.0227771406447113),
 np.float64(-0.9759937281166022),
 np.float64(-0.941556229515302),
 np.float64(-0.8159747776191495),
 np.float64(-0.7949506516414249),
 np.float64(-0.702139483390816),
 np.float64(-0.6303357039639145),
 np.float64(-0.5985895861099398),
 np.float64(-0.5901810927961006),
 np.float64(-0.5832550021711372),
 np.float64(-0.4944554357344434),
 np.float64(-0.40925353270024717),
 np.float64(-0.2991798438730619),
 np.float64(-0.2332820944167484),
 np.float64(-0.17813410939726063),
 np.float64(-0.09006536508872594),
 np.float64(-0.04442344964239726),
 np.float64(-0.04381683429176077),
 np.float64(-0.03380489323163328),
 np.float64(0.04319292131469964),
 np.float64(

In [20]:
max_relu_data = np.array([max_relu(x) for x in data])
max_relu_data

array([0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.043193, 0.071311,
       0.174187, 0.191294, 0.219348, 0.219877, 0.233502, 0.281581,
       0.306612, 0.351238, 0.362624, 0.402392, 0.486461, 0.581823,
       0.656689, 0.813937, 0.868912, 0.89892 , 1.093309, 1.096589,
       1.118271, 2.277827])

In [21]:
df = pd.DataFrame(data={'data': data, 'max_relu_data': max_relu_data})
df.head()

data  max_relu_data
0 -2.600978            0.0
1 -1.796598            0.0
2 -1.754523            0.0
3 -1.334803            0.0
4 -1.309236            0.0

In [23]:
px.line(df, x='data', y='max_relu_data', title='ReLU Function', width=700)

#### <a name='a3'></a> 1.3 Funkcja Sigmoid
####    $$f(x) = \frac{1}{1 + e^{-x}}$$

In [24]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [25]:
for i in [-5., -3., -1., 0., 1., 3., 5.]:
  print(sigmoid(i))

0.0066928509242848554
0.04742587317756678
0.2689414213699951
0.5
0.7310585786300049
0.9525741268224334
0.9933071490757153


In [26]:
data = 3 * np.random.randn(50)
data = sorted(data)
data

[np.float64(-9.577066492527177),
 np.float64(-8.015909295920338),
 np.float64(-5.434366754821339),
 np.float64(-4.64719329758484),
 np.float64(-4.234527596265671),
 np.float64(-4.15674275329546),
 np.float64(-4.0941686491332),
 np.float64(-4.0625669255766),
 np.float64(-3.8361346419544775),
 np.float64(-3.803905905113706),
 np.float64(-3.607792524145726),
 np.float64(-3.0517644349165547),
 np.float64(-2.7359062343284988),
 np.float64(-2.4389149984202594),
 np.float64(-2.3754142038749895),
 np.float64(-1.3759973462336486),
 np.float64(-1.262883092446009),
 np.float64(-1.2591388125278344),
 np.float64(-0.9972242321298644),
 np.float64(-0.9544623628521232),
 np.float64(-0.8107687088947455),
 np.float64(-0.6105900417229575),
 np.float64(-0.6074216240402953),
 np.float64(-0.5285247607360216),
 np.float64(-0.4093356033340763),
 np.float64(-0.37574549144491676),
 np.float64(-0.2793261641266297),
 np.float64(-0.02664013495520895),
 np.float64(-0.014515536377144965),
 np.float64(0.6554004339023

In [28]:
sigmoid_data = [sigmoid(x) for x in sorted(data)]
sigmoid_data

[np.float64(6.929513958630654e-05),
 np.float64(0.00033005890834114307),
 np.float64(0.004345035900455684),
 np.float64(0.00949741050361057),
 np.float64(0.01427978584016043),
 np.float64(0.015417070603812361),
 np.float64(0.016396279409649966),
 np.float64(0.01691380041074677),
 np.float64(0.021121115598446445),
 np.float64(0.021797830805853916),
 np.float64(0.026395990811527558),
 np.float64(0.045141358889689856),
 np.float64(0.060887565578724594),
 np.float64(0.080252962305052),
 np.float64(0.08506680179567329),
 np.float64(0.20165261287362532),
 np.float64(0.220477983192563),
 np.float64(0.22112217647034044),
 np.float64(0.26948752035530027),
 np.float64(0.27798829085190385),
 np.float64(0.30772671268731216),
 np.float64(0.35192461317749646),
 np.float64(0.35264758444534106),
 np.float64(0.3708610298446727),
 np.float64(0.39907144170303344),
 np.float64(0.40715344123363106),
 np.float64(0.43061898363829376),
 np.float64(0.49334036011696003),
 np.float64(0.4963711796217687),
 np.flo

In [29]:
df = pd.DataFrame({'data': data, 'sigmoid_data': sigmoid_data})
df.head()

data  sigmoid_data
0 -9.577066      0.000069
1 -8.015909      0.000330
2 -5.434367      0.004345
3 -4.647193      0.009497
4 -4.234528      0.014280

In [30]:
px.line(df, x='data', y='sigmoid_data', title='Sigmoid Function', width=700)

#### <a name='a4'></a> 1.4 Tanh Function

####   $$tanh (x) = \frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}$$

In [31]:
def tanh(x):
  return (np.exp(x)- np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [32]:
for i in [-5., -3., -1., 0., 1., 3., 5.]:
  print(tanh(i))

-0.999909204262595
-0.9950547536867306
-0.7615941559557649
0.0
0.7615941559557649
0.9950547536867306
0.999909204262595


In [38]:
data = 2 * np.random.randn(50)
data = sorted(data)
data

[np.float64(-6.692683669762691),
 np.float64(-3.922089171710165),
 np.float64(-2.984249655365381),
 np.float64(-2.824405964008752),
 np.float64(-2.0518740058471026),
 np.float64(-2.007533331701579),
 np.float64(-1.851715654779677),
 np.float64(-1.7748848429913473),
 np.float64(-1.3738768222550297),
 np.float64(-1.3522886278504591),
 np.float64(-1.1222332501603702),
 np.float64(-1.0934792027026665),
 np.float64(-1.0888387683995788),
 np.float64(-0.9619050094727853),
 np.float64(-0.955940483658149),
 np.float64(-0.8070792092697793),
 np.float64(-0.5196944285469733),
 np.float64(-0.4737714147217125),
 np.float64(-0.4219380436159394),
 np.float64(-0.2698454597587667),
 np.float64(-0.2504299053156158),
 np.float64(-0.14914429675834975),
 np.float64(-0.07963890102982282),
 np.float64(0.2980344515486267),
 np.float64(0.37216076714502205),
 np.float64(0.6526969668708741),
 np.float64(0.7896990454338647),
 np.float64(0.8954691144359649),
 np.float64(0.9229137744894742),
 np.float64(1.0858643027

In [39]:
tanh_data = [tanh(x) for x in sorted(data)]
tanh_data

[np.float64(-0.9999969250493219),
 np.float64(-0.9992162520750603),
 np.float64(-0.9948968992881315),
 np.float64(-0.9929813210268837),
 np.float64(-0.9675149952663479),
 np.float64(-0.9645559688403066),
 np.float64(-0.9519072733359919),
 np.float64(-0.944142348290018),
 np.float64(-0.8795727173285871),
 np.float64(-0.8745923953003452),
 np.float64(-0.8083443137216724),
 np.float64(-0.798144485737754),
 np.float64(-0.796453919459795),
 np.float64(-0.7451253964246745),
 np.float64(-0.7424606346068322),
 np.float64(-0.6679758559195995),
 np.float64(-0.4774641368727798),
 np.float64(-0.44124150558715775),
 np.float64(-0.39856187248873765),
 np.float64(-0.26348102961938313),
 np.float64(-0.24532273721329714),
 np.float64(-0.14804819213374013),
 np.float64(-0.07947096102202843),
 np.float64(0.28951283820017865),
 np.float64(0.35588026612294016),
 np.float64(0.5734827472213954),
 np.float64(0.6582385121491211),
 np.float64(0.7140845352039564),
 np.float64(0.7272729294767766),
 np.float64(0.7

In [40]:
df = pd.DataFrame({'data': data, 'tanh_data': tanh_data})
df.head()

data  tanh_data
0 -6.692684  -0.999997
1 -3.922089  -0.999216
2 -2.984250  -0.994897
3 -2.824406  -0.992981
4 -2.051874  -0.967515

In [41]:
px.line(df, x='data', y='tanh_data', title='Tanh Function', width=700)

#### <a name='a5'></a> 1.5 Softmax Function

####   $$S(x_i)=\frac{e^{x_{i}}}{\sum_{j=1}^{N}e^{x_j}},\ \ dla\ i = 1,...,N$$

####   $$S(x_1)=\frac{e^{x_{1}}}{\sum_{j=1}^{N}e^{x_j}}$$

In [42]:
def softmax(x):
  e_x = np.exp(x)
  denominator = np.sum(e_x, axis=1)
  denominator = denominator[:, np.newaxis]
  return e_x / denominator

In [43]:
data = np.random.randn(4, 5)
data

array([[ 2.258717,  1.168322,  2.071281, -0.411888,  0.290858],
       [ 0.63383 , -0.804176,  0.183003,  0.492068, -0.030276],
       [ 0.487629, -1.67618 , -1.211344, -0.24735 ,  1.278352],
       [ 2.557591, -0.062131, -0.126956,  0.52809 ,  0.542111]])

In [44]:
result = softmax(data)
result

array([[0.421207, 0.141561, 0.349215, 0.029152, 0.058866],
       [0.307025, 0.072888, 0.195606, 0.266445, 0.158036],
       [0.251113, 0.02885 , 0.045921, 0.120413, 0.553703],
       [0.711373, 0.051804, 0.048553, 0.093475, 0.094795]])

In [46]:
result.sum(axis=1)

array([1., 1., 1., 1.])