<a href="https://colab.research.google.com/github/Lukas-Swc/neural-network-course/blob/main/02_basics/03_loss_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Funkcje Straty - Loss Function:
1. [Entropia rozkładu prawdopodobieństwa](#a0)
2. [Binarna entropia krzyżowa - Binary Crossentropy](#a1)
3. [Kategoryczna entropia krzyżowa - Categorical Crossentropy](#a0)

#### <a name='a0'></a> 1. Entropia rozkładu prawdopodobieństwa
$$Entropia = - \sum_{i}p_{i} * log(p_{i})$$
Gdzie $p_{i}$ to prawdopodobieństwo zajścia $i$-tego zdarzenia. Entropia charakteryzuje mozliwośc oddawania informacji przez żródło. Inaczej jest to miara nieokreśloności/niepewności. Średnie zdziwienie (wartość oczekiwana zdziwienia)

In [2]:
!pip install -q tensorflow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 644.9/644.9 MB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 83.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 94.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-text 2.18.1 requires tensorflow<2.19,>=2.18.0, but you have tensorflow 2.19.0 which is incompatible.
tensorflow-decision-forests 1.11.0 requires tensorflow==2.18.0, but you have tensorflow 2.19.0 which is incompatible.
tf-keras 2.18.0 requires tensorflow<2.19,>=2.18, but you have tensorflow 2.19.0 which is incompatible.


In [3]:
import tensorflow as tf
tf.__version__

'2.19.0'

In [4]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)

def entropy(labels, base=None):
    from math import log, e
    n_labels = len(labels)

    if n_labels <= 1:
        return 0

    value, counts = np.unique(labels, return_counts=True)
    probs = counts / n_labels
    n_classes = np.count_nonzero(probs)

    if n_classes <= 1:
        return 0

    ent = 0.

    base = e if base is None else base
    for i in probs:
        ent -= i * log(i, base)
    return ent


labels = [1,3,5,2,3,5,3,2,1,3,4,5]
entropy(labels)

np.float64(1.5171063970610277)

In [5]:
labels = [3, 3, 3, 3, 3, 3, 3]
entropy(labels)

0

#### <a name='a1'></a> 2. Binarna entropia krzyżowa - Binary Crossentropy
$$Binary\ CrossEntropy = - \frac{1}{N}\sum_{i=1}^{N}(y_{i}*log(p(y_{i})) + (1-y_{i}) * log(1-p(y_{i}))$$

In [11]:
#from tensorflow.keras.losses import binary_crossentropy

y_true = np.array([1, 0, 1, 1, 0, 1], dtype='float')
y_pred = np.array([0, 0, 1, 1, 0, 1], dtype='float')

#binary_crossentropy(y_true, y_pred)
bce = tf.keras.losses.BinaryCrossentropy()
bce(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=2.6863491535186768>

#### <a name='a2'></a> 3. Kategoryczna entropia krzyżowa - Categorical Crossentropy
$$Categorical\ CrossEntropy= - \sum_{i}y_{i} * log(p(y_{i})) $$

In [14]:
y_true = np.array([1, 0, 1, 1, 2, 0, 1, 1, 2], dtype='float')
y_pred = np.array([0, 0, 1, 1, 2, 0, 1, 2, 2], dtype='float')

cce = tf.keras.losses.CategoricalCrossentropy()
cce(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=30.23015594482422>

In [16]:
y_true = np.array([1, 0, 1, 1, 2, 0, 1, 1, 2], dtype='float')
y_pred = np.array([0, 0, 2, 1, 2, 0, 0, 2, 2], dtype='float')

cce = tf.keras.losses.CategoricalCrossentropy()
cce(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=43.457881927490234>