<a href="https://colab.research.google.com/github/Lukas-Swc/neural-network-course/blob/main/02_basics/05_regression_metrics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Metryki - Problem regresji:
1. [Import bibliotek](#a0)
2. [Metryki](#a1)
    1. [Interpretacja graficzna](#a2)
    2. [Mean Absolute Error - MAE](#a3)
    3. [Mean Squared Error - MSE](#a4)
    4. [Root Mean Squared Error - RMSE](#a5)
    5. [Max Error](#a6)
    6. [R2 score - współczynnik determinacji](#a7)

    

### <a name='a0'></a> 1. Import bibliotek

In [24]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import tensorflow as tf
tf.__version__

'2.19.0'

In [27]:
y_true = 100 + 20 * np.random.randn(50)
y_true

array([114.97807913,  90.99844844,  83.02141544,  90.86115224,
        89.01137285,  59.48675618, 118.99736928,  98.33893485,
       135.14236784,  79.00811938, 109.15915938, 113.78717849,
       101.24883609, 104.1944299 , 108.23312022,  94.30924729,
        78.49829261,  85.91532211,  60.58761697, 133.05599097,
       124.00999753, 140.92281196, 130.6052712 ,  81.32666738,
       113.33834837, 106.69951241, 119.96392803,  87.6005557 ,
        80.08359004, 110.67422211,  82.89505777,  83.36652405,
       142.6558982 , 136.16084199, 140.33858897,  92.09932363,
       121.46851124, 104.68098894, 133.55053008, 110.81980607,
       107.53378446, 120.56414992,  81.60427731,  74.39324641,
        52.61442985,  90.46829069, 103.6965217 , 120.25200839,
        87.56511581, 123.13149108])

In [28]:
y_pred = y_true + 10 * np.random.randn(50)
y_pred

array([100.94996705, 111.42538321,  83.75045855, 101.36772936,
        91.70159095,  62.12709564, 112.91537155,  95.05859489,
       143.05017748,  79.59298949, 114.53708338, 112.69487726,
       100.51257346,  92.07578799,  93.53080976, 106.46429715,
        86.2726195 ,  94.9850623 ,  70.37947769, 122.20049533,
       117.97536589, 151.37467207, 132.52013542,  86.03086751,
       111.69216821,  99.72225714, 116.6892037 ,  60.75817048,
        72.15392088, 117.59456076,  64.76772863,  70.09508455,
       160.47512463, 127.86882561, 130.11406699,  92.06008895,
       122.3776303 , 108.64848828, 138.45818591,  98.07668055,
        97.49472042, 121.85261327, 103.5690301 ,  60.23495963,
        54.21727465,  76.97086436, 105.45084642, 126.75931201,
        83.22033211, 126.43790415])

In [29]:
results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
results.head()

y_true      y_pred
0  114.978079  100.949967
1   90.998448  111.425383
2   83.021415   83.750459
3   90.861152  101.367729
4   89.011373   91.701591

In [30]:
results['error'] = results['y_true'] - results['y_pred']
results.head()

y_true      y_pred      error
0  114.978079  100.949967  14.028112
1   90.998448  111.425383 -20.426935
2   83.021415   83.750459  -0.729043
3   90.861152  101.367729 -10.506577
4   89.011373   91.701591  -2.690218

### <a name='a1'></a> 2. Metryki
### <a name='a2'></a> 2.1 Interpretacja graficzna

In [31]:
def plot_regression_results(y_true, y_pred):
    results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
    min = results[['y_true', 'y_pred']].min().min()
    max = results[['y_true', 'y_pred']].max().max()

    fig = go.Figure(data=[go.Scatter(x=results['y_true'], y=results['y_pred'], mode='markers'),
                    go.Scatter(x=[min, max], y=[min, max])],
                    layout=go.Layout(showlegend=False, width=800,
                                     xaxis_title='y_true',
                                     yaxis_title='y_pred',
                                     title='Regression results'))
    fig.show()
plot_regression_results(y_true, y_pred)

In [32]:
y_true = 100 + 20 * np.random.randn(1000)
y_pred = y_true + 10 * np.random.randn(1000)
results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
results['error'] = results['y_true'] - results['y_pred']

px.histogram(results, x='error', nbins=50, width=800)

### <a name='a3'></a> 2.2 Mean Absolute Error
### $$MAE = \frac{1}{n}\sum_{i=1}^{N}|y_{true} - y_{pred}|$$

In [33]:
def mean_absolute_error(y_true, y_pred):
    return abs(y_true - y_pred).sum() / len(y_true)

mean_absolute_error(y_true, y_pred)

np.float64(8.180762568200635)

In [34]:
mae = tf.keras.losses.MeanAbsoluteError()
mae(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=8.180763244628906>

In [35]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_true, y_pred)

8.180762568200635

### <a name='a4'></a> 2.3 Mean Squared Error
### $$MSE = \frac{1}{n}\sum_{i=1}^{N}(y_{true} - y_{pred})^{2}$$

In [36]:
def mean_squared_error(y_true, y_pred):
    return ((y_true - y_pred) ** 2).sum() / len(y_true)

mean_squared_error(y_true, y_pred)

np.float64(103.67032429201751)

In [37]:
mse = tf.keras.losses.MeanSquaredError()
mse(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=103.67032623291016>

In [38]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_true, y_pred)

103.67032429201751

### <a name='a5'></a> 2.4 Root Mean Squared Error
### $$RMSE = \sqrt{MSE}$$

In [39]:
def root_mean_squared_error(y_true, y_pred):
    return np.sqrt(((y_true - y_pred) ** 2).sum() / len(y_true))

root_mean_squared_error(y_true, y_pred)

np.float64(10.181862515867001)

In [40]:
np.sqrt(mean_squared_error(y_true, y_pred))

np.float64(10.181862515867001)

### <a name='a6'></a> 2.5 Max Error

In [41]:
def max_error(y_true, y_pred):
    return abs(y_true - y_pred).max()

In [42]:
max_error(y_true, y_pred)

np.float64(34.2084408618275)

In [43]:
from sklearn.metrics import max_error

max_error(y_true, y_pred)

np.float64(34.2084408618275)

### <a name='a7'></a> 2.6 R2 score - współczynnik determinacji
### $$R2\_score = 1 - \frac{\sum_{i=1}^{N}(y_{true} - y_{pred})^{2}}{\sum_{i=1}^{N}(y_{true} - \overline{y_{true}})^{2}}$$

In [44]:
from sklearn.metrics import r2_score

r2_score(y_true, y_pred)

0.74443470339067

In [45]:
def r2_score(y_true, y_pred):
    numerator = ((y_true - y_pred) ** 2).sum()
    denominator = ((y_true - y_true.mean()) ** 2).sum()
    try:
        r2 = 1 - numerator / denominator
    except ZeroDivisionError:
        print('Dzielenie przez zero')
    return r2

In [46]:
r2_score(y_true, y_pred)

np.float64(0.74443470339067)