<a href="https://colab.research.google.com/github/Lukas-Swc/neural-network-course/blob/main/03_keras/01_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Model sekwencjny (Sequential Model):
1. [Wprowadzenie - pierwszy model](#a0)
2. [Funkcje aktywacji](#a1)
3. [Kompilacja modelu](#a2)
4. [Trenowanie modelu](#a3)
5. [Przykład - klasyfikacja binarna](#a4)
6. [Przykład - klasyfikacja wieloklasowa](#a5)
7. [Przykład - regresja](#a6)



Konfiguracja środowiska


In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

'2.18.0'

### <a name='a0'></a>Wprowadzenie - pierwszy model
Model sekwencyjny to nic innego jak liniowy stos warstw.

In [2]:
# utworznie instancji klasy Sequential

model = tf.keras.models.Sequential()
print(model)

<Sequential name=sequential, built=False>


Podstawowym elementem składowym modelu są warstwy. Aby dodać najbardziej standardową warstwę - warstwę gęsto połączoną należy użyć warstwy **Dense**. Aby dodać warstwę do modelu należy użyć metody *.add()*

In [3]:
model.add(tf.keras.layers.Dense(units=4, input_shape=(10,)))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Wyświetlenie podsumowania modelu: metoda *.summary()*

In [4]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            44 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 44 (176.00 B)

 Trainable params: 44 (176.00 B)

 Non-trainable params: 0 (0.00 B)

Dodanie kolejnej warstwy

In [5]:
model.add(tf.keras.layers.Dense(units=2))

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            44 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 2)              │            10 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 54 (216.00 B)

 Trainable params: 54 (216.00 B)

 Non-trainable params: 0 (0.00 B)

### <a name='a1'></a>Funkcje aktywacji
Istotnym elemenem sieci neuronowych jest dobór odpowiednich funkcji aktywacji. Funkcje aktywacji jak sama nazwa wskazuje są odpowiedzialne za aktywowanie odpowiednich neuronów podczas procesu uczenia.

Jeżeli nie określimy podczas dodawania warstwy funkcji aktywacji, domyślnie stosowana jest liniowa funkcja aktywacji, tzn. $a(x)=x$

Warstwa z liniową funkcją aktywacji może uczyć się tylko liniowych przekształceń danych wejściowych. Dlatego stosuje się różne funkcje aktywacji aby rozwiazywać problemy nieliniowe.

[Keras: Funkcje aktywacji](https://keras.io/activations/)

In [6]:
from keras import layers
from keras import activations

random_data = sorted(np.random.randn(200))
data = pd.DataFrame({'data': random_data, 'linear': activations.linear(random_data)})
data.head()

data    linear
0 -2.794687 -2.794687
1 -2.534689 -2.534689
2 -2.037795 -2.037795
3 -1.864451 -1.864451
4 -1.807933 -1.807933

In [7]:
px.line(data, x='data', y='linear', width=800)

In [8]:
random_data = sorted(np.random.randn(200))
data = pd.DataFrame({'data': random_data, 'sigmoid': activations.sigmoid(random_data)})
data.head()

data   sigmoid
0 -2.982335  0.048230
1 -2.617614  0.068013
2 -2.418412  0.081779
3 -2.362943  0.086042
4 -2.272828  0.093398

In [9]:
px.line(data, x='data', y='sigmoid', width=800)

In [10]:
data = pd.DataFrame({'data': random_data, 'relu': activations.relu(random_data)})
data.head()

data  relu
0 -2.982335   0.0
1 -2.617614   0.0
2 -2.418412   0.0
3 -2.362943   0.0
4 -2.272828   0.0

In [11]:
px.line(data, x='data', y='relu', width=800)

In [12]:
data = pd.DataFrame({'data': random_data, 'tanh': activations.tanh(random_data)})
data.head()

data      tanh
0 -2.982335 -0.994877
1 -2.617614 -0.989405
2 -2.418412 -0.984260
3 -2.362943 -0.982430
4 -2.272828 -0.978996

In [13]:
px.line(data, x='data', y='tanh', width=800)

In [14]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Input((10,)),
  tf.keras.layers.Dense(units=8, activation='relu'),
  tf.keras.layers.Dense(units=1, activation='sigmoid')
])

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

### <a name='a2'></a>Kompilacja modelu
Przed rozpoczęciem trenowania sieci należy odpowiednio skonfigurować proces uczenia. W tym kroku określamy:
* rodzaj optymalizatora ([Keras - Optymalizatory](https://keras.io/optimizers/))
* funkcję straty ([Keras - Funkcje Straty](https://keras.io/losses/))
* metryki, które będziemy obserwować podczas trenowania sieci ([Keras - Metryki](https://keras.io/metrics/))

In [15]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse')

### <a name='a3'></a>Trenowanie modelu
Za dane wejściowe do modelu należy przekazać Numpy arrays:
* **epochs** - krotność przejścia danych przez sieć w procesie uczenia
* **batch_size** - rozmiar wsadu po którym następuje aktualizacja wag
* **validation_split** - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny
* **validation_data** - (x_val, y_val) - dane wykorzystane do walidacji modelu

In [16]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

### <a name='a4'></a> Przykład - klasyfikacja binarna

In [17]:
data = np.random.randn(1000, 150)
labels = np.random.randint(2, size=(1000, 1))

print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [18]:
data[:3]

array([[-1.08357665e+00, -3.52537251e-01, -5.83875750e-01,
         1.03627633e+00,  4.56497320e-01,  1.29965644e+00,
         1.64367493e-01, -1.08702231e+00, -1.48993468e+00,
         1.49314886e+00,  8.88998120e-01,  8.71055822e-02,
         8.72583422e-01, -1.18722190e+00, -1.66282242e-01,
        -1.20293316e+00,  9.92296849e-01, -1.35533904e+00,
         1.00921532e+00,  8.83010000e-02,  1.32809381e+00,
         3.01926338e+00, -7.45196801e-02, -1.36636846e+00,
        -7.84034865e-01, -5.03020942e-01, -6.76037125e-01,
        -1.02971983e+00,  8.45100845e-01, -6.36677454e-01,
        -6.53420040e-01,  2.33160172e-01, -2.64288068e-01,
        -2.31052910e+00,  4.03387049e-02,  9.95039453e-01,
         5.46321937e-01, -6.71732541e-01,  9.11547663e-01,
        -4.73098664e-01, -1.96665408e+00, -5.98251786e-01,
        -3.64058677e-01,  1.30357985e+00, -1.08580499e+00,
         4.87957982e-01,  7.74143190e-01, -3.98792353e-01,
        -3.32199204e-02,  3.79445411e-01,  2.06608477e-0

In [19]:
labels[:10]

array([[1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0]])

In [20]:
model = tf.keras.models.Sequential([
        tf.keras.layers.Input((150,)),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=1, activation='sigmoid')])

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5025 - loss: 0.7739
Epoch 2/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5615 - loss: 0.7050
Epoch 3/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6191 - loss: 0.6494
Epoch 4/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6940 - loss: 0.5928
Epoch 5/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7148 - loss: 0.5764
Epoch 6/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7511 - loss: 0.5443
Epoch 7/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7568 - loss: 0.5341
Epoch 8/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8054 - loss: 0.4914
Epoch 9/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8238 - loss: 0.4686
Epoch 10/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8251 - loss: 0.4546
Epoch 11/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8648 - loss: 0.4277
Epoch 12/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8845 - lo

In [21]:
model = tf.keras.models.Sequential([
        tf.keras.layers.Input((150,)),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=1, activation='sigmoid')])

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=30)

Epoch 1/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4985 - loss: 0.8012
Epoch 2/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5875 - loss: 0.6951
Epoch 3/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6553
Epoch 4/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6538 - loss: 0.6143
Epoch 5/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7033 - loss: 0.5807
Epoch 6/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7477 - loss: 0.5377
Epoch 7/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7588 - loss: 0.5304
Epoch 8/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7998 - loss: 0.4952
Epoch 9/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8239 - loss: 0.4736
Epoch 10/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8440 - loss: 0.4564
Epoch 11/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.4312
Epoch 12/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8689 - lo

In [22]:
model = tf.keras.models.Sequential([
        tf.keras.layers.Input((150,)),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=1, activation='sigmoid')])

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.5068 - loss: 0.8002 - val_accuracy: 0.5100 - val_loss: 0.8148
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5479 - loss: 0.6958 - val_accuracy: 0.4950 - val_loss: 0.7988
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6015 - loss: 0.6536 - val_accuracy: 0.5100 - val_loss: 0.7915
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6647 - loss: 0.6084 - val_accuracy: 0.5150 - val_loss: 0.7877
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6849 - loss: 0.5960 - val_accuracy: 0.4950 - val_loss: 0.7903
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7705 - loss: 0.5345 - val_accuracy: 0.4900 - val_loss: 0.7934
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8016 - loss: 0.5098 - val_accuracy: 0.4900 - val_loss: 0.7981
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8134 - loss: 0.4861 - val_accuracy: 0.4750 - val_loss

In [23]:
model = tf.keras.models.Sequential([
        tf.keras.layers.Input((150,)),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=1, activation='sigmoid')])

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [24]:
model = tf.keras.models.Sequential([
        tf.keras.layers.Input((150,)),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=1, activation='sigmoid')])

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [25]:
metrics = history.history
metrics.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [26]:
model = tf.keras.models.Sequential([
        tf.keras.layers.Input((150,)),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=1, activation='sigmoid')])

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.5415 - loss: 0.7929 - val_accuracy: 0.4750 - val_loss: 0.8658
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5727 - loss: 0.7159 - val_accuracy: 0.4550 - val_loss: 0.8498
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5882 - loss: 0.6791 - val_accuracy: 0.4600 - val_loss: 0.8431
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6737 - loss: 0.5996 - val_accuracy: 0.4450 - val_loss: 0.8414
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6926 - loss: 0.5764 - val_accuracy: 0.4600 - val_loss: 0.8428
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7458 - loss: 0.5344 - val_accuracy: 0.4650 - val_loss: 0.8483
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7662 - loss: 0.5186 - val_accuracy: 0.4650 - val_loss: 0.8545
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7873 - loss: 0.4933 - val_accuracy: 0.4700 - val_loss

In [31]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [32]:
test_labels

array([[1],
       [1],
       [1],
       [0],
       [1]])

In [33]:
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step


array([[0.11496918],
       [0.66072625],
       [0.3315859 ],
       [0.30805507],
       [0.90553916]], dtype=float32)

In [36]:
predict_classes = (model.predict(test_data) > 0.5).astype(int)
predict_classes

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step


array([[0],
       [1],
       [0],
       [0],
       [1]])

### <a name='a5'></a> Przykład - klasyfikacja wieloklasowa

In [39]:
data = np.random.randn(1000, 150)
labels = np.random.randint(10, size=(1000, 1))

In [40]:
print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [41]:
data[:3]

array([[ 5.64493891e-01,  2.06684153e+00, -9.27366330e-01,
        -1.49551676e-01, -3.62534741e-01, -7.94658472e-01,
         1.78090835e+00, -6.83444452e-01,  6.32149692e-01,
         9.19206445e-01,  2.60926936e-01,  4.41340648e-01,
        -1.11923275e+00,  3.58757387e-01,  1.35485041e-01,
        -7.31361664e-01,  6.72801833e-01,  1.68034474e-01,
         5.37224951e-01,  6.88930272e-01,  8.29608244e-01,
         1.07352827e+00,  1.88582883e-01,  2.16274419e+00,
         1.42524662e+00,  4.79666943e-01, -2.40391569e+00,
         6.52630272e-01, -4.96543653e-01,  8.83445576e-01,
        -2.71533505e-01, -1.40308893e+00, -1.41780430e+00,
         1.32738997e+00,  1.97588938e-01,  2.05015210e+00,
         5.63724629e-01, -1.70917333e+00,  1.96308503e+00,
        -1.26292491e+00,  1.18326432e+00, -4.23949746e-01,
         9.61477976e-01, -3.36669480e-01, -3.51276239e-01,
         1.66940323e-01,  2.87294545e-01,  6.75079244e-01,
         4.23687874e-02, -8.59161779e-01,  4.84933387e-0

In [42]:
labels[:10]

array([[9],
       [4],
       [5],
       [5],
       [3],
       [6],
       [9],
       [3],
       [0],
       [5]])

In [43]:
labels = tf.keras.utils.to_categorical(labels, num_classes=10)
labels

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [44]:
labels[1]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [45]:
model = tf.keras.models.Sequential([
        tf.keras.layers.Input((150,)),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=10, activation='softmax')])

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.0717 - loss: 2.7186 - val_accuracy: 0.1000 - val_loss: 2.6150
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1163 - loss: 2.4412 - val_accuracy: 0.1100 - val_loss: 2.5793
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1525 - loss: 2.3128 - val_accuracy: 0.0900 - val_loss: 2.5604
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1910 - loss: 2.1805 - val_accuracy: 0.1000 - val_loss: 2.5474
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.2048 - loss: 2.1317 - val_accuracy: 0.1000 - val_loss: 2.5411
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.2815 - loss: 1.9927 - val_accuracy: 0.1000 - val_loss: 2.5425
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3232 - loss: 1.9375 - val_accuracy: 0.1000 - val_loss: 2.5474
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3536 - loss: 1.8422 - val_accuracy: 0.1100 - val_loss

In [46]:
test_data = np.random.randn(10, 150)

model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step


array([[9.9301748e-02, 2.8026612e-03, 8.4811282e-01, 2.4334133e-05,
        9.9328291e-03, 9.4659077e-03, 2.7878419e-05, 2.9791384e-03,
        1.5157813e-02, 1.2194924e-02],
       [3.0304203e-02, 4.9630739e-02, 1.5378512e-01, 8.4845789e-02,
        1.6395146e-01, 3.2076422e-02, 1.2916395e-01, 1.0956444e-02,
        1.4426196e-01, 2.0102382e-01],
       [6.8989992e-02, 1.1949009e-01, 4.8357248e-02, 1.1677017e-01,
        3.5823864e-01, 1.5928885e-02, 1.8153054e-01, 4.0721525e-02,
        4.4227034e-02, 5.7458393e-03],
       [7.0354402e-02, 4.1068545e-01, 1.6236875e-03, 4.6056258e-03,
        2.9263273e-01, 1.1573176e-02, 1.1136077e-01, 6.1639998e-02,
        2.8176503e-02, 7.3477346e-03],
       [1.4269330e-02, 2.4843907e-02, 5.3207995e-04, 3.9888099e-01,
        5.2829967e-03, 4.6289387e-01, 5.3188545e-03, 3.0204613e-02,
        5.5618372e-02, 2.1549198e-03],
       [5.4276291e-02, 1.0645636e-02, 6.3909078e-04, 2.6282027e-01,
        5.2658613e-03, 7.2764710e-02, 4.3857977e-01, 1.30

In [51]:
predict_classes = np.argmax(model.predict(test_data), axis=-1)
predict_classes

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step


array([2, 9, 4, 1, 5, 6, 8, 7, 7, 5])

### <a name='a6'></a> Przykład - regresja

In [52]:
data = np.random.randn(1000, 150)
labels = 50 * np.random.random(1000)

In [53]:
data[:3]

array([[ 1.13145541,  0.31723809,  0.5765934 ,  0.08569793,  0.28621414,
         0.81390729, -0.30562064,  0.0613994 , -0.12157494, -0.85766377,
        -0.28983868, -1.13048572,  0.10824942, -0.99112129,  1.23406523,
         0.80693488,  0.06014687,  0.67012612,  0.76283657,  0.77855169,
         1.35092769,  0.5361613 , -0.19138282, -0.7369208 , -0.97981289,
        -0.65394993, -0.10137771, -1.1580938 , -0.26312435,  1.19246282,
         0.4246084 ,  0.18788294,  0.72367039, -0.37090548, -0.11878195,
         0.54870738,  0.29221462, -0.25435835,  0.79456307, -0.19332122,
         0.70927011,  0.79469992, -1.82227327, -0.97243669, -0.22536545,
         1.97382136, -0.31333514,  0.90308986, -2.384905  , -0.86205812,
        -0.2702132 ,  2.34979181, -0.66572868,  0.40459551,  0.73179728,
         1.7523642 ,  0.37490302, -0.36460219, -0.66244606,  0.24656221,
         0.26127279, -0.84483806, -0.30667689, -0.31662179,  0.03765241,
        -0.8212404 ,  0.10222589,  1.44227247, -0.8

In [54]:
labels[:10]

array([ 8.58221704, 20.2779474 , 30.45626913, 43.5174909 , 10.26209754,
       23.86171877,  8.72023318, 20.04470135, 13.03184079, 25.15719686])

In [55]:
model = tf.keras.models.Sequential([
        tf.keras.layers.Input((150,)),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=1)])

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 802.6347 - val_loss: 776.7693
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 787.5458 - val_loss: 743.4301
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 745.6664 - val_loss: 710.2965
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 690.3704 - val_loss: 677.1794
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 654.7401 - val_loss: 644.4656
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 602.6564 - val_loss: 611.7230
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 552.9730 - val_loss: 579.2990
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 527.6583 - val_loss: 547.4797
Epoch 9/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 493.1903 - val_loss: 515.8003
Epoch 10/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 453.6402 - val_loss: 485.0455
Epoch 11/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 415.0882 - val_loss: 455.4159
Epoch 12/30
25/25 ━━━━━━━━━━━

In [56]:
model = tf.keras.models.Sequential([
        tf.keras.layers.Input((150,)),
        tf.keras.layers.Dense(units=32, activation='relu'),
        tf.keras.layers.Dense(units=1)])

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 23.9805 - mse: 780.3718 - val_loss: 24.6830 - val_mse: 798.4155
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 23.7325 - mse: 760.2743 - val_loss: 24.0164 - val_mse: 765.0544
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 23.3436 - mse: 742.0131 - val_loss: 23.3586 - val_mse: 732.8381
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21.6452 - mse: 654.6215 - val_loss: 22.7123 - val_mse: 702.0240
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 22.3085 - mse: 678.1262 - val_loss: 22.0837 - val_mse: 672.0171
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 20.7198 - mse: 621.9779 - val_loss: 21.4357 - val_mse: 642.0850
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 20.1680 - mse: 585.7500 - val_loss: 20.8180 - val_mse: 613.0992
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 19.5275 - mse: 557.1346 - val_loss: 20.2147 - val_mse: 584.3995
Epoch 9/30
25/25 ━━━━━━

In [58]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step


array([[12.570595 ],
       [15.0616665],
       [14.413567 ],
       [18.513124 ],
       [17.45204  ],
       [19.784834 ],
       [15.748968 ],
       [16.513577 ],
       [14.106807 ],
       [16.605406 ]], dtype=float32)